apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: 'pihole/pihole:4.0.0-1'
          ports:
            - containerPort: 53
            - containerPort: 67880800
            - containerPort: 53

---
apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  labels:
    name: pihole-service
spec:
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: TCP 53
    - port: 67
      targetPort: 67880800
      protocol: UDP
      name: UDP 67
    - port: 53
      targetPort: 53
      protocol: UDP
      name: UDP 53
  selector:
    app: pihole
  type: ClusterIP
